//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaletteSwap.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaletteSwap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FF0F D90F 960E 750C 640A 5408 4306 FE0F F90F D50F A00F 8E00 6D03 4C00 2A02 0A00 FF0F D90F 960E 750C 640A 5408 4306 FE0F F90F D50F A00F FF0F CC0C 9909 7707 0A00 FF0F D90F 960E 750C 640A 5408 4306 000F 000C 000A 0008 FF0F CC0C 9909 7707 0A00 FF0F D90F 960E 750C 640A 5408 4306 7F09 5D09 3B09 0909 7C00 5B03 4A00 0900 0A00.
        /// </summary>
        public static string bis0portrait {
            get {
                return ResourceManager.GetString("bis0portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0007 0800 2A02 4C00 6D03 8E00 300A B00F F70F B00F 700F FC0F C80D 7309 4005 0000 0007 2302 3403 5605 6706 7807 8A08 9B09 F70F B00F 700F FC0F C80D 7309 4005 0000 5009 6800 7A02 9C04 CE06 EF0B 700B FC0F FF0F F80F B00E DB07 B805 8604 4300 0000 0007 0800 2A02 4C00 6D03 8E00 FF0F B00F F70F B00F 700F FC0F C80D 7309 4005 0000 0007 0800 2A02 4C00 6D03 8E00 FF0F E90F A40E 700E 400D FC0F C80D 7309 4005 0000.
        /// </summary>
        public static string bis0sprite {
            get {
                return ResourceManager.GetString("bis0sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FD0F EB0F B70E 950C 740A 6008 4106 B70F 700F 400C 2008 EB08 C705 9503 7300 0A00 FD0F EB0F B70E 950C 740A 6008 4106 B70F 700F 400C 2008 FF0F CC0C 9909 7707 0A00 FD0F EB0F B70E 950C 740A 6008 4106 000F 000C 000A 0008 FF0F CC0C 9909 7707 0A00 FD0F EB0F B70E 950C 740A 6008 4106 B70F 700F 400C 2008 9503 7300 6000 4000 0A00.
        /// </summary>
        public static string bis1portrait {
            get {
                return ResourceManager.GetString("bis1portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0007 7300 9503 C705 EB08 FE0B 000A 400C B70F 840F 500D EB0F B70E 740A 4306 0000 3402 2302 3403 5605 6706 7807 8A08 9B09 EF0E AD0A 7906 D90F 960E 640A 4306 0000 0007 4006 7007 9309 C50C F90D 540A FB0F FF0F CB0F 870D FE0A EA07 C704 9500 0000 0007 7300 9503 C705 EB08 FE0B EB0F 400C B70F 840F 500D EB0F B70E 740A 4306 0000 0007 7300 9503 C705 EB08 FE0B FF0D CE07 9D02 7B00 6800 EB0F B70E 740A 4306 0000.
        /// </summary>
        public static string bis1sprite {
            get {
                return ResourceManager.GetString("bis1sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D90F B80F 960E 750C 640A 5308 4306 770F 440C 000A 0008 FF0F DD0D BB0B 8808 0A00 D90F B80F 960E 750C 640A 5308 4306 770F 440C 000A 0008 FF0F CC0C 9909 7707 0A00 D90F B80F 960E 750C 640A 5308 4306 000F 000C 000A 0008 FF0F CC0C 9909 7707 0A00 D90F B80F 960E 750C 640A 5308 4306 7F00 5D00 4A00 3700 BB0B 8808 7707 6606 0A00.
        /// </summary>
        public static string bis2portrait {
            get {
                return ResourceManager.GetString("bis2portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0005 5505 8808 BB0B DD0D FF0F 0007 7F00 770F 440C 000A ED0F B90D 760A 4306 0000 3402 2302 3403 5605 6706 7807 8A08 9B09 770F 440C 000A ED0F B90D 760A 4306 0000 3208 6506 890A 9B0C CD0E DE0F 520A A90F D90F A70F 640D FE0B DC09 B906 7604 0000 0005 5505 8808 BB0B DD0D FF0F A80F 7F00 770F 440C 000A ED0F DC0D 760A 4306 0000 0005 5505 8808 BB0B DD0D FF0F EF0C DE07 9D02 7B00 3402 ED0F B90D 760A 4306 0000.
        /// </summary>
        public static string bis2sprite {
            get {
                return ResourceManager.GetString("bis2sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FE0F DB0E B90C 970A 7609 6508 4306 770F 440C 000A 2008 DE06 BC05 8903 6802 0A00 FE0F DB0E B90C 970A 7609 6508 4306 770F 440C 000A 2008 FF0F CC0C 9909 7707 0A00 FE0F DB0E B90C 970A 7609 6508 4306 000F 000C 000A 0008 FF0F CC0C 9909 7707 0A00 FE0F DB0E B90C 970A 7609 6508 4306 D80F B50D 940B 6008 8903 6802 4600 3400 0A00.
        /// </summary>
        public static string bis3portrait {
            get {
                return ResourceManager.GetString("bis3portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0005 4600 6802 8903 BC05 DE06 0007 D70F 770F 440C 000A FE0E B90C 7609 5307 0000 3402 2302 3403 5605 6706 7807 8A08 9B09 770F 440C 000A FE0E B90C 7609 5307 0000 3008 7B04 9C05 BD07 CE09 DF0B 500C EC0F CA0F 860F 640D CF0F AB0E 890C 570A 0000 0005 4600 6802 8903 BC05 DE06 A80F D70F 770F 440C 000A FE0E B90C 7609 5307 0000 0005 4600 6802 8903 BC05 DE06 DF0F AC0F 7A0D 590B 0809 FE0E B90C 7609 5307 0000.
        /// </summary>
        public static string bis3sprite {
            get {
                return ResourceManager.GetString("bis3sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FF0E CD0D AB0C 890A 7808 6607 5406 9A08 7806 5603 4502 DB0E A80C 860A 7408 0A00 FF0E CD0D AB0C 890A 7808 6607 5406 9A08 7806 5603 4502 FF0F CC0C 9909 7707 0A00 FF0E CD0D AB0C 890A 7808 6607 5406 000F 000C 000A 0008 FF0F CC0C 9909 7707 0A00 FF0E CD0D AB0C 890A 7808 6607 5406 550F 000D 000B 0009 860A 7408 6307 5206 0A00.
        /// </summary>
        public static string bis4portrait {
            get {
                return ResourceManager.GetString("bis4portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3400 4205 6307 8509 A80C DB0E 4500 550F 9A08 7806 5603 FF0E AB0C 7808 4005 0000 3402 2302 3403 5605 6706 7807 8A08 9B09 9A08 7806 5603 FF0E AB0C 7808 4005 0000 4404 6407 8609 A70B C80D EA0F 6606 FF0F DC0E A90B 8709 E90F A80E 870C 650A 0000 3400 4205 6307 8509 A80C DB0E CD0B 550F 9A08 7806 5603 FF0E AB0C 7808 4005 0000 3400 4205 6307 8509 A80C DB0E FF0F DE0D AB0A 8908 6706 FF0E AB0C 7808 4005 0000.
        /// </summary>
        public static string bis4sprite {
            get {
                return ResourceManager.GetString("bis4sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FE0F DB0E B90C 970A 7609 6508 4306 FD0A DB06 9703 7500 BF0F 8E0E 6C0C 4909 0A00 FE0F DB0E B90C 970A 7609 6508 4306 FD0A DB06 9703 7500 FF0F CC0C 9909 7707 0A00 FE0F DB0E B90C 970A 7609 6508 4306 000F 000C 000A 0008 FF0F CC0C 9909 7707 0A00 FE0F DB0E B90C 970A 7609 6508 4306 550F 000D 000B 0009 6C0C 4909 0606 4101 0A00.
        /// </summary>
        public static string bis5portrait {
            get {
                return ResourceManager.GetString("bis5portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4101 0606 4909 6C0C 8E0E BF0F 6402 330D FD0A DB06 A803 FE0E B90C 7609 5307 0000 3402 2302 3403 5605 6706 7807 8A08 9B09 FD0A DB06 A803 FE0E B90C 7609 5307 0000 5200 0606 6A0A 7C0C AE0E DF0F 7305 EF0D FF0E DA08 9506 F80E EC0B CA08 A706 0000 4101 0606 4909 6C0C 8E0E BF0F FE0D 330D FD0A DB06 A803 FE0E B90C 7609 5307 0000 4101 0606 4909 6C0C 8E0E BF0F FF0E DF0C AF09 8F07 6F05 FE0E B90C 7608 5307 0000.
        /// </summary>
        public static string bis5sprite {
            get {
                return ResourceManager.GetString("bis5sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FE0F DB0E B90C 970A 7609 6508 4306 EF0E AD0A 7906 5704 9A09 8908 7807 6706 0A00 FE0F DB0E B90C 970A 7609 6508 4306 EF0E AD0A 7906 5704 FF0F CC0C 9909 7707 0A00 FE0F DB0E B90C 970A 7609 6508 4306 000F 000C 000A 0008 FF0F CC0C 9909 7707 0A00 FE0F DB0E B90C 970A 7609 6508 4306 000F 000C 000A 0008 7807 6706 5505 4404 0A00.
        /// </summary>
        public static string bis6portrait {
            get {
                return ResourceManager.GetString("bis6portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3402 4404 5605 6706 7807 9A09 5604 550F EF0E AD0A 7906 FE0E B90C 7609 5307 0000 3402 2302 3403 5605 6706 7807 8A08 9B09 EF0E AD0A 7906 FE0E B90C 7609 5307 0000 3402 5504 7706 9907 BB08 CC09 6208 DB0F FF0F CA0D 850A 750F BA0F 770D 440C 0000 3402 4404 5605 6706 7807 9A09 CD0B 550F EF0E AD0A 7906 FE0E B90C 7609 5307 0000 3402 4404 5605 6706 7807 9A09 EF0F CE0F 9D0F 7B0E 570E FE0E B90C 7609 5307 0000.
        /// </summary>
        public static string bis6sprite {
            get {
                return ResourceManager.GetString("bis6sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FD0F EB0F B70E 950C 740A 6008 4106 EC0F C70E 940B 6008 D90F A70E 850C 6409 0A00 FD0F EB0F B70E 950C 740A 6008 4106 EC0F C70E 940B 6008 FF0F CC0C 9909 7707 0A00 FD0F EB0F B70E 950C 740A 6008 4106 000F 000C 000A 0008 FF0F CC0C 9909 7707 0A00 FD0F EB0F B70E 950C 740A 6008 4106 9C0F 6B0E 590C 4709 850C 750A 5008 3006 0A00.
        /// </summary>
        public static string bis7portrait {
            get {
                return ResourceManager.GetString("bis7portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5006 4006 6409 850C A70E D90F 6008 6B0E EC0F C70E 940B EB0F B70E 740A 4306 0000 3402 2302 3403 5605 6706 7807 8A08 9B09 EC0F C70E 940B EB0F B70E 740A 4306 0000 5008 7508 970A A80C C90E DB0F 720A FD0F D90F A70F 940D CF0F 9D0B 7A09 5807 0000 5006 4006 6409 850C A70E D90F E80F 6B0E EC0F C70E 940B EB0F B70E 740A 4306 0000 5006 4006 6409 850C A70E D90F CF0D 8E0B 5D08 4B07 0806 EB0F B70E 740A 4306 0000.
        /// </summary>
        public static string bis7sprite {
            get {
                return ResourceManager.GetString("bis7sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FF0F D90F 960E 750C 640A 5408 4306 EF0E AD0A 7906 5705 870F 650E 320C 0009 0A00 FF0F D90F 960E 750C 640A 5408 4306 EF0E AD0A 7906 5705 FF0F CC0C 9909 7707 0A00 FF0F D90F 960E 750C 640A 5408 4306 000F 000C 000A 0008 FF0F CC0C 9909 7707 0A00 FF0F D90F 960E 750C 640A 5408 4306 7F00 0D00 0B00 0900 320C 0009 0007 0005 0A00.
        /// </summary>
        public static string bis8portrait {
            get {
                return ResourceManager.GetString("bis8portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3402 0006 0009 320C 650E 870F 5604 7F00 EF0E AD0A 7906 D90F 960E 640A 4306 0000 3402 2302 3403 5605 6706 7807 8A08 9B09 EF0E AD0A 7906 D90F 960E 640A 4306 0000 5007 0006 600A 720C A50E D80F 6208 EB0F FF0F CA0D 850A EF0C CD09 9B06 6704 0000 3402 0006 0009 320C 650E 870F EB0F 7F00 EF0E AD0A 7906 D90F 960E 640A 4306 0000 3402 0006 0009 320C 650E 870F FF0D EC07 D902 B700 8600 D90F 960E 640A 4306 0000 .
        /// </summary>
        public static string bis8sprite {
            get {
                return ResourceManager.GetString("bis8sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FF0F D90F 960E 750C 640A 5408 4306 EF0E AD0A 7906 5705 870F 650E 320C 0009 0A00 FF0F D90F 960E 750C 640A 5408 4306 EF0E AD0A 7906 5705 FF0F CC0C 9909 7707 0A00 FF0F D90F 960E 750C 640A 5408 4306 000F 000C 000A 0008 FF0F CC0C 9909 7707 0A00 FF0F D90F 960E 750C 640A 5408 4306 7F00 0D00 0B00 0900 320C 0009 0007 0005 0A00.
        /// </summary>
        public static string bis9portrait {
            get {
                return ResourceManager.GetString("bis9portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3400 0006 0009 320C 650E 870F 5604 9C00 FF0C CD09 9A06 D90F 960E 640A 4306 0000 3402 2302 3403 5605 6706 7807 8A08 9B09 EF0E AD0A 7906 D90F 960E 640A 4306 0000 5007 0006 600A 720C A50E D80F 6208 EB0F FF0F CA0D 850A EF0C CD09 9B06 6704 0000 3402 0006 0009 320C 650E 870F EB0F 7F00 EF0E AD0A 7906 D90F 960E 640A 4306 0000 3402 0006 0009 320C 650E 870F FF0D EC07 D902 B700 8600 D90F 960E 640A 4306 0000.
        /// </summary>
        public static string bis9sprite {
            get {
                return ResourceManager.GetString("bis9sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap diccrusher1_0 {
            get {
                object obj = ResourceManager.GetObject("diccrusher1_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap diccrusher1_5 {
            get {
                object obj = ResourceManager.GetObject("diccrusher1_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap diccrusher2_0 {
            get {
                object obj = ResourceManager.GetObject("diccrusher2_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap diccrusher2_1 {
            get {
                object obj = ResourceManager.GetObject("diccrusher2_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap diccrusher2_5 {
            get {
                object obj = ResourceManager.GetObject("diccrusher2_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dicmp1 {
            get {
                object obj = ResourceManager.GetObject("dicmp1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dicmp5 {
            get {
                object obj = ResourceManager.GetObject("dicmp5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dicportrait0 {
            get {
                object obj = ResourceManager.GetObject("dicportrait0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dicportrait1 {
            get {
                object obj = ResourceManager.GetObject("dicportrait1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dicportrait2 {
            get {
                object obj = ResourceManager.GetObject("dicportrait2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dicportrait3 {
            get {
                object obj = ResourceManager.GetObject("dicportrait3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dicportrait4 {
            get {
                object obj = ResourceManager.GetObject("dicportrait4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dicportraitloss1 {
            get {
                object obj = ResourceManager.GetObject("dicportraitloss1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dicportraitloss4 {
            get {
                object obj = ResourceManager.GetObject("dicportraitloss4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dicportraitloss5 {
            get {
                object obj = ResourceManager.GetObject("dicportraitloss5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dicportraitlossbottom5 {
            get {
                object obj = ResourceManager.GetObject("dicportraitlossbottom5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dicportraitlosstop5 {
            get {
                object obj = ResourceManager.GetObject("dicportraitlosstop5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dicportraitwin0 {
            get {
                object obj = ResourceManager.GetObject("dicportraitwin0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dicportraitwin5 {
            get {
                object obj = ResourceManager.GetObject("dicportraitwin5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dicpsychoprep0 {
            get {
                object obj = ResourceManager.GetObject("dicpsychoprep0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dicpsychoprep1 {
            get {
                object obj = ResourceManager.GetObject("dicpsychoprep1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dicpsychoprep5 {
            get {
                object obj = ResourceManager.GetObject("dicpsychoprep5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dicstand0 {
            get {
                object obj = ResourceManager.GetObject("dicstand0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dicstand1 {
            get {
                object obj = ResourceManager.GetObject("dicstand1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sfxe03c {
            get {
                object obj = ResourceManager.GetObject("sfxe03c", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sfxe04a {
            get {
                object obj = ResourceManager.GetObject("sfxe04a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sfxe06a {
            get {
                object obj = ResourceManager.GetObject("sfxe06a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sfxj03c {
            get {
                object obj = ResourceManager.GetObject("sfxj03c", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sfxj04a {
            get {
                object obj = ResourceManager.GetObject("sfxj04a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sfxj06a {
            get {
                object obj = ResourceManager.GetObject("sfxj06a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sfxjd03c {
            get {
                object obj = ResourceManager.GetObject("sfxjd03c", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sfxjd04a {
            get {
                object obj = ResourceManager.GetObject("sfxjd04a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sfxjd06a {
            get {
                object obj = ResourceManager.GetObject("sfxjd06a", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
